// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.0--rc2
// source: Sophon.proto

package utils

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chunk 模式游戏文件清单
type SophonChunkManifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chuncks []*SophonChunkFile `protobuf:"bytes,1,rep,name=chuncks,proto3" json:"chuncks,omitempty"`
}

func (x *SophonChunkManifest) Reset() {
	*x = SophonChunkManifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sophon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SophonChunkManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonChunkManifest) ProtoMessage() {}

func (x *SophonChunkManifest) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonChunkManifest.ProtoReflect.Descriptor instead.
func (*SophonChunkManifest) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{0}
}

func (x *SophonChunkManifest) GetChuncks() []*SophonChunkFile {
	if x != nil {
		return x.Chuncks
	}
	return nil
}

// Chunk 模式游戏文件
type SophonChunkFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File     string         `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Chunks   []*SophonChunk `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	IsFolder bool           `protobuf:"varint,3,opt,name=is_folder,json=isFolder,proto3" json:"is_folder,omitempty"`
	Size     int64          `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Md5      string         `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`
}

func (x *SophonChunkFile) Reset() {
	*x = SophonChunkFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sophon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SophonChunkFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonChunkFile) ProtoMessage() {}

func (x *SophonChunkFile) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonChunkFile.ProtoReflect.Descriptor instead.
func (*SophonChunkFile) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{1}
}

func (x *SophonChunkFile) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SophonChunkFile) GetChunks() []*SophonChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *SophonChunkFile) GetIsFolder() bool {
	if x != nil {
		return x.IsFolder
	}
	return false
}

func (x *SophonChunkFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SophonChunkFile) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

// Chunk 模式游戏文件块
type SophonChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UncompressedMd5  string `protobuf:"bytes,2,opt,name=uncompressed_md5,json=uncompressedMd5,proto3" json:"uncompressed_md5,omitempty"`
	Offset           int64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	CompressedSize   int64  `protobuf:"varint,4,opt,name=compressed_size,json=compressedSize,proto3" json:"compressed_size,omitempty"`
	UncompressedSize int64  `protobuf:"varint,5,opt,name=uncompressed_size,json=uncompressedSize,proto3" json:"uncompressed_size,omitempty"`
	Unknown          int64  `protobuf:"varint,6,opt,name=unknown,proto3" json:"unknown,omitempty"`
	CompressedMd5    string `protobuf:"bytes,7,opt,name=compressed_md5,json=compressedMd5,proto3" json:"compressed_md5,omitempty"`
}

func (x *SophonChunk) Reset() {
	*x = SophonChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Sophon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SophonChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonChunk) ProtoMessage() {}

func (x *SophonChunk) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonChunk.ProtoReflect.Descriptor instead.
func (*SophonChunk) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{2}
}

func (x *SophonChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SophonChunk) GetUncompressedMd5() string {
	if x != nil {
		return x.UncompressedMd5
	}
	return ""
}

func (x *SophonChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SophonChunk) GetCompressedSize() int64 {
	if x != nil {
		return x.CompressedSize
	}
	return 0
}

func (x *SophonChunk) GetUncompressedSize() int64 {
	if x != nil {
		return x.UncompressedSize
	}
	return 0
}

func (x *SophonChunk) GetUnknown() int64 {
	if x != nil {
		return x.Unknown
	}
	return 0
}

func (x *SophonChunk) GetCompressedMd5() string {
	if x != nil {
		return x.CompressedMd5
	}
	return ""
}

var File_Sophon_proto protoreflect.FileDescriptor

var file_Sophon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x53, 0x6f, 0x70, 0x68, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41,
	0x0a, 0x13, 0x53, 0x6f, 0x70, 0x68, 0x6f, 0x6e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x4d, 0x61, 0x6e,
	0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x63, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x53, 0x6f, 0x70, 0x68, 0x6f, 0x6e, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x63, 0x6b,
	0x73, 0x22, 0x8e, 0x01, 0x0a, 0x0f, 0x53, 0x6f, 0x70, 0x68, 0x6f, 0x6e, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x6f, 0x70, 0x68,
	0x6f, 0x6e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x64, 0x35, 0x22, 0xf7, 0x01, 0x0a, 0x0b, 0x53, 0x6f, 0x70, 0x68, 0x6f, 0x6e, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x75, 0x6e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x64, 0x5f, 0x6d, 0x64, 0x35, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x75, 0x6e,
	0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x4d, 0x64, 0x35, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e,
	0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2b,
	0x0a, 0x11, 0x75, 0x6e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x75, 0x6e, 0x63, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x64, 0x5f, 0x6d, 0x64, 0x35, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x4d, 0x64, 0x35, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Sophon_proto_rawDescOnce sync.Once
	file_Sophon_proto_rawDescData = file_Sophon_proto_rawDesc
)

func file_Sophon_proto_rawDescGZIP() []byte {
	file_Sophon_proto_rawDescOnce.Do(func() {
		file_Sophon_proto_rawDescData = protoimpl.X.CompressGZIP(file_Sophon_proto_rawDescData)
	})
	return file_Sophon_proto_rawDescData
}

var file_Sophon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Sophon_proto_goTypes = []interface{}{
	(*SophonChunkManifest)(nil), // 0: SophonChunkManifest
	(*SophonChunkFile)(nil),     // 1: SophonChunkFile
	(*SophonChunk)(nil),         // 2: SophonChunk
}
var file_Sophon_proto_depIdxs = []int32{
	1, // 0: SophonChunkManifest.chuncks:type_name -> SophonChunkFile
	2, // 1: SophonChunkFile.chunks:type_name -> SophonChunk
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Sophon_proto_init() }
func file_Sophon_proto_init() {
	if File_Sophon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Sophon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SophonChunkManifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Sophon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SophonChunkFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Sophon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SophonChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Sophon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Sophon_proto_goTypes,
		DependencyIndexes: file_Sophon_proto_depIdxs,
		MessageInfos:      file_Sophon_proto_msgTypes,
	}.Build()
	File_Sophon_proto = out.File
	file_Sophon_proto_rawDesc = nil
	file_Sophon_proto_goTypes = nil
	file_Sophon_proto_depIdxs = nil
}
