// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: Sophon.proto

package utils

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chunk 模式游戏文件清单
type SophonChunkManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chuncks       []*SophonChunkFile     `protobuf:"bytes,1,rep,name=chuncks,proto3" json:"chuncks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonChunkManifest) Reset() {
	*x = SophonChunkManifest{}
	mi := &file_Sophon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonChunkManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonChunkManifest) ProtoMessage() {}

func (x *SophonChunkManifest) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonChunkManifest.ProtoReflect.Descriptor instead.
func (*SophonChunkManifest) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{0}
}

func (x *SophonChunkManifest) GetChuncks() []*SophonChunkFile {
	if x != nil {
		return x.Chuncks
	}
	return nil
}

// Chunk 模式游戏文件
type SophonChunkFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Chunks        []*SophonChunk         `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	IsFolder      bool                   `protobuf:"varint,3,opt,name=is_folder,json=isFolder,proto3" json:"is_folder,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Md5           string                 `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonChunkFile) Reset() {
	*x = SophonChunkFile{}
	mi := &file_Sophon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonChunkFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonChunkFile) ProtoMessage() {}

func (x *SophonChunkFile) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonChunkFile.ProtoReflect.Descriptor instead.
func (*SophonChunkFile) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{1}
}

func (x *SophonChunkFile) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SophonChunkFile) GetChunks() []*SophonChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *SophonChunkFile) GetIsFolder() bool {
	if x != nil {
		return x.IsFolder
	}
	return false
}

func (x *SophonChunkFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SophonChunkFile) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

// Chunk 模式游戏文件块
type SophonChunk struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UncompressedMd5  string                 `protobuf:"bytes,2,opt,name=uncompressed_md5,json=uncompressedMd5,proto3" json:"uncompressed_md5,omitempty"`
	Offset           int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	CompressedSize   int64                  `protobuf:"varint,4,opt,name=compressed_size,json=compressedSize,proto3" json:"compressed_size,omitempty"`
	UncompressedSize int64                  `protobuf:"varint,5,opt,name=uncompressed_size,json=uncompressedSize,proto3" json:"uncompressed_size,omitempty"`
	Unknown          int64                  `protobuf:"varint,6,opt,name=unknown,proto3" json:"unknown,omitempty"`
	CompressedMd5    string                 `protobuf:"bytes,7,opt,name=compressed_md5,json=compressedMd5,proto3" json:"compressed_md5,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SophonChunk) Reset() {
	*x = SophonChunk{}
	mi := &file_Sophon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonChunk) ProtoMessage() {}

func (x *SophonChunk) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonChunk.ProtoReflect.Descriptor instead.
func (*SophonChunk) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{2}
}

func (x *SophonChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SophonChunk) GetUncompressedMd5() string {
	if x != nil {
		return x.UncompressedMd5
	}
	return ""
}

func (x *SophonChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SophonChunk) GetCompressedSize() int64 {
	if x != nil {
		return x.CompressedSize
	}
	return 0
}

func (x *SophonChunk) GetUncompressedSize() int64 {
	if x != nil {
		return x.UncompressedSize
	}
	return 0
}

func (x *SophonChunk) GetUnknown() int64 {
	if x != nil {
		return x.Unknown
	}
	return 0
}

func (x *SophonChunk) GetCompressedMd5() string {
	if x != nil {
		return x.CompressedMd5
	}
	return ""
}

// Patch 更新模式游戏文件清单
type SophonPatchManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 新版本所有文件
	Patches []*SophonPatchFile `protobuf:"bytes,1,rep,name=patches,proto3" json:"patches,omitempty"`
	// 需要删除的文件
	DeleteTags []*SophonPatchDeleteTag `protobuf:"bytes,2,rep,name=delete_tags,json=deleteTags,proto3" json:"delete_tags,omitempty"`
	// 压缩模式
	CompressMode  int32 `protobuf:"varint,3,opt,name=compress_mode,json=compressMode,proto3" json:"compress_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonPatchManifest) Reset() {
	*x = SophonPatchManifest{}
	mi := &file_Sophon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatchManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatchManifest) ProtoMessage() {}

func (x *SophonPatchManifest) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatchManifest.ProtoReflect.Descriptor instead.
func (*SophonPatchManifest) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{3}
}

func (x *SophonPatchManifest) GetPatches() []*SophonPatchFile {
	if x != nil {
		return x.Patches
	}
	return nil
}

func (x *SophonPatchManifest) GetDeleteTags() []*SophonPatchDeleteTag {
	if x != nil {
		return x.DeleteTags
	}
	return nil
}

func (x *SophonPatchManifest) GetCompressMode() int32 {
	if x != nil {
		return x.CompressMode
	}
	return 0
}

// Patch 更新模式，新版本游戏文件
type SophonPatchFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	File  string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Size  int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Md5   string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	// 不同版本的补丁文件，如果为空则表示不需要更新
	Patches       []*SophonPatchInfo `protobuf:"bytes,4,rep,name=patches,proto3" json:"patches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonPatchFile) Reset() {
	*x = SophonPatchFile{}
	mi := &file_Sophon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatchFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatchFile) ProtoMessage() {}

func (x *SophonPatchFile) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatchFile.ProtoReflect.Descriptor instead.
func (*SophonPatchFile) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{4}
}

func (x *SophonPatchFile) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SophonPatchFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SophonPatchFile) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *SophonPatchFile) GetPatches() []*SophonPatchInfo {
	if x != nil {
		return x.Patches
	}
	return nil
}

type SophonPatchInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 更新前游戏版本
	Tag           string       `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Patch         *SophonPatch `protobuf:"bytes,2,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonPatchInfo) Reset() {
	*x = SophonPatchInfo{}
	mi := &file_Sophon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatchInfo) ProtoMessage() {}

func (x *SophonPatchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatchInfo.ProtoReflect.Descriptor instead.
func (*SophonPatchInfo) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{5}
}

func (x *SophonPatchInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SophonPatchInfo) GetPatch() *SophonPatch {
	if x != nil {
		return x.Patch
	}
	return nil
}

// Patch 更新模式，游戏文件补丁，注意：每个补丁都很小，一个文件中可能有多个补丁
type SophonPatch struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag     string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	BuildId string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// 文件大小
	PatchFileSize int64  `protobuf:"varint,4,opt,name=patch_file_size,json=patchFileSize,proto3" json:"patch_file_size,omitempty"`
	PatchFileMd5  string `protobuf:"bytes,5,opt,name=patch_file_md5,json=patchFileMd5,proto3" json:"patch_file_md5,omitempty"`
	// 当前游戏文件补丁的偏移量
	PatchOffset int64 `protobuf:"varint,6,opt,name=patch_offset,json=patchOffset,proto3" json:"patch_offset,omitempty"`
	// 当前游戏文件补丁的长度
	PatchLength int64 `protobuf:"varint,7,opt,name=patch_length,json=patchLength,proto3" json:"patch_length,omitempty"`
	// 如果有这个值，表示需要使用 hdiffpatch 更新，没有表示这是新文件，对应的补丁就是原文件，直接复制即可
	OriginalFileName string `protobuf:"bytes,8,opt,name=original_file_name,json=originalFileName,proto3" json:"original_file_name,omitempty"`
	OriginalFileSize int64  `protobuf:"varint,9,opt,name=original_file_size,json=originalFileSize,proto3" json:"original_file_size,omitempty"`
	OriginalFileMd5  string `protobuf:"bytes,10,opt,name=original_file_md5,json=originalFileMd5,proto3" json:"original_file_md5,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SophonPatch) Reset() {
	*x = SophonPatch{}
	mi := &file_Sophon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatch) ProtoMessage() {}

func (x *SophonPatch) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatch.ProtoReflect.Descriptor instead.
func (*SophonPatch) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{6}
}

func (x *SophonPatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SophonPatch) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SophonPatch) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SophonPatch) GetPatchFileSize() int64 {
	if x != nil {
		return x.PatchFileSize
	}
	return 0
}

func (x *SophonPatch) GetPatchFileMd5() string {
	if x != nil {
		return x.PatchFileMd5
	}
	return ""
}

func (x *SophonPatch) GetPatchOffset() int64 {
	if x != nil {
		return x.PatchOffset
	}
	return 0
}

func (x *SophonPatch) GetPatchLength() int64 {
	if x != nil {
		return x.PatchLength
	}
	return 0
}

func (x *SophonPatch) GetOriginalFileName() string {
	if x != nil {
		return x.OriginalFileName
	}
	return ""
}

func (x *SophonPatch) GetOriginalFileSize() int64 {
	if x != nil {
		return x.OriginalFileSize
	}
	return 0
}

func (x *SophonPatch) GetOriginalFileMd5() string {
	if x != nil {
		return x.OriginalFileMd5
	}
	return ""
}

type SophonPatchDeleteTag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 更新前游戏版本
	Tag              string                           `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	DeleteCollection *SophonPatchDeleteFileCollection `protobuf:"bytes,2,opt,name=delete_collection,json=deleteCollection,proto3" json:"delete_collection,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SophonPatchDeleteTag) Reset() {
	*x = SophonPatchDeleteTag{}
	mi := &file_Sophon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatchDeleteTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatchDeleteTag) ProtoMessage() {}

func (x *SophonPatchDeleteTag) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatchDeleteTag.ProtoReflect.Descriptor instead.
func (*SophonPatchDeleteTag) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{7}
}

func (x *SophonPatchDeleteTag) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SophonPatchDeleteTag) GetDeleteCollection() *SophonPatchDeleteFileCollection {
	if x != nil {
		return x.DeleteCollection
	}
	return nil
}

type SophonPatchDeleteFileCollection struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	DeleteFiles   []*SophonPatchDeleteFile `protobuf:"bytes,1,rep,name=delete_files,json=deleteFiles,proto3" json:"delete_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonPatchDeleteFileCollection) Reset() {
	*x = SophonPatchDeleteFileCollection{}
	mi := &file_Sophon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatchDeleteFileCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatchDeleteFileCollection) ProtoMessage() {}

func (x *SophonPatchDeleteFileCollection) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatchDeleteFileCollection.ProtoReflect.Descriptor instead.
func (*SophonPatchDeleteFileCollection) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{8}
}

func (x *SophonPatchDeleteFileCollection) GetDeleteFiles() []*SophonPatchDeleteFile {
	if x != nil {
		return x.DeleteFiles
	}
	return nil
}

// Patch 更新模式，需要删除文件
type SophonPatchDeleteFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Md5           string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SophonPatchDeleteFile) Reset() {
	*x = SophonPatchDeleteFile{}
	mi := &file_Sophon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SophonPatchDeleteFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SophonPatchDeleteFile) ProtoMessage() {}

func (x *SophonPatchDeleteFile) ProtoReflect() protoreflect.Message {
	mi := &file_Sophon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SophonPatchDeleteFile.ProtoReflect.Descriptor instead.
func (*SophonPatchDeleteFile) Descriptor() ([]byte, []int) {
	return file_Sophon_proto_rawDescGZIP(), []int{9}
}

func (x *SophonPatchDeleteFile) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SophonPatchDeleteFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SophonPatchDeleteFile) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

var File_Sophon_proto protoreflect.FileDescriptor

const file_Sophon_proto_rawDesc = "" +
	"\n" +
	"\fSophon.proto\x12\x18Starward.RPC.GameInstall\"Z\n" +
	"\x13SophonChunkManifest\x12C\n" +
	"\achuncks\x18\x01 \x03(\v2).Starward.RPC.GameInstall.SophonChunkFileR\achuncks\"\xa7\x01\n" +
	"\x0fSophonChunkFile\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12=\n" +
	"\x06chunks\x18\x02 \x03(\v2%.Starward.RPC.GameInstall.SophonChunkR\x06chunks\x12\x1b\n" +
	"\tis_folder\x18\x03 \x01(\bR\bisFolder\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x10\n" +
	"\x03md5\x18\x05 \x01(\tR\x03md5\"\xf7\x01\n" +
	"\vSophonChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10uncompressed_md5\x18\x02 \x01(\tR\x0funcompressedMd5\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12'\n" +
	"\x0fcompressed_size\x18\x04 \x01(\x03R\x0ecompressedSize\x12+\n" +
	"\x11uncompressed_size\x18\x05 \x01(\x03R\x10uncompressedSize\x12\x18\n" +
	"\aunknown\x18\x06 \x01(\x03R\aunknown\x12%\n" +
	"\x0ecompressed_md5\x18\a \x01(\tR\rcompressedMd5\"\xd0\x01\n" +
	"\x13SophonPatchManifest\x12C\n" +
	"\apatches\x18\x01 \x03(\v2).Starward.RPC.GameInstall.SophonPatchFileR\apatches\x12O\n" +
	"\vdelete_tags\x18\x02 \x03(\v2..Starward.RPC.GameInstall.SophonPatchDeleteTagR\n" +
	"deleteTags\x12#\n" +
	"\rcompress_mode\x18\x03 \x01(\x05R\fcompressMode\"\x90\x01\n" +
	"\x0fSophonPatchFile\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5\x12C\n" +
	"\apatches\x18\x04 \x03(\v2).Starward.RPC.GameInstall.SophonPatchInfoR\apatches\"`\n" +
	"\x0fSophonPatchInfo\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12;\n" +
	"\x05patch\x18\x02 \x01(\v2%.Starward.RPC.GameInstall.SophonPatchR\x05patch\"\xe6\x02\n" +
	"\vSophonPatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\x12&\n" +
	"\x0fpatch_file_size\x18\x04 \x01(\x03R\rpatchFileSize\x12$\n" +
	"\x0epatch_file_md5\x18\x05 \x01(\tR\fpatchFileMd5\x12!\n" +
	"\fpatch_offset\x18\x06 \x01(\x03R\vpatchOffset\x12!\n" +
	"\fpatch_length\x18\a \x01(\x03R\vpatchLength\x12,\n" +
	"\x12original_file_name\x18\b \x01(\tR\x10originalFileName\x12,\n" +
	"\x12original_file_size\x18\t \x01(\x03R\x10originalFileSize\x12*\n" +
	"\x11original_file_md5\x18\n" +
	" \x01(\tR\x0foriginalFileMd5\"\x90\x01\n" +
	"\x14SophonPatchDeleteTag\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12f\n" +
	"\x11delete_collection\x18\x02 \x01(\v29.Starward.RPC.GameInstall.SophonPatchDeleteFileCollectionR\x10deleteCollection\"u\n" +
	"\x1fSophonPatchDeleteFileCollection\x12R\n" +
	"\fdelete_files\x18\x01 \x03(\v2/.Starward.RPC.GameInstall.SophonPatchDeleteFileR\vdeleteFiles\"Q\n" +
	"\x15SophonPatchDeleteFile\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5BFZ)github.com/sffxzzp/GenshinSymlinker/utils\xaa\x02\x18Starward.RPC.GameInstallb\x06proto3"

var (
	file_Sophon_proto_rawDescOnce sync.Once
	file_Sophon_proto_rawDescData []byte
)

func file_Sophon_proto_rawDescGZIP() []byte {
	file_Sophon_proto_rawDescOnce.Do(func() {
		file_Sophon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Sophon_proto_rawDesc), len(file_Sophon_proto_rawDesc)))
	})
	return file_Sophon_proto_rawDescData
}

var file_Sophon_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_Sophon_proto_goTypes = []any{
	(*SophonChunkManifest)(nil),             // 0: Starward.RPC.GameInstall.SophonChunkManifest
	(*SophonChunkFile)(nil),                 // 1: Starward.RPC.GameInstall.SophonChunkFile
	(*SophonChunk)(nil),                     // 2: Starward.RPC.GameInstall.SophonChunk
	(*SophonPatchManifest)(nil),             // 3: Starward.RPC.GameInstall.SophonPatchManifest
	(*SophonPatchFile)(nil),                 // 4: Starward.RPC.GameInstall.SophonPatchFile
	(*SophonPatchInfo)(nil),                 // 5: Starward.RPC.GameInstall.SophonPatchInfo
	(*SophonPatch)(nil),                     // 6: Starward.RPC.GameInstall.SophonPatch
	(*SophonPatchDeleteTag)(nil),            // 7: Starward.RPC.GameInstall.SophonPatchDeleteTag
	(*SophonPatchDeleteFileCollection)(nil), // 8: Starward.RPC.GameInstall.SophonPatchDeleteFileCollection
	(*SophonPatchDeleteFile)(nil),           // 9: Starward.RPC.GameInstall.SophonPatchDeleteFile
}
var file_Sophon_proto_depIdxs = []int32{
	1, // 0: Starward.RPC.GameInstall.SophonChunkManifest.chuncks:type_name -> Starward.RPC.GameInstall.SophonChunkFile
	2, // 1: Starward.RPC.GameInstall.SophonChunkFile.chunks:type_name -> Starward.RPC.GameInstall.SophonChunk
	4, // 2: Starward.RPC.GameInstall.SophonPatchManifest.patches:type_name -> Starward.RPC.GameInstall.SophonPatchFile
	7, // 3: Starward.RPC.GameInstall.SophonPatchManifest.delete_tags:type_name -> Starward.RPC.GameInstall.SophonPatchDeleteTag
	5, // 4: Starward.RPC.GameInstall.SophonPatchFile.patches:type_name -> Starward.RPC.GameInstall.SophonPatchInfo
	6, // 5: Starward.RPC.GameInstall.SophonPatchInfo.patch:type_name -> Starward.RPC.GameInstall.SophonPatch
	8, // 6: Starward.RPC.GameInstall.SophonPatchDeleteTag.delete_collection:type_name -> Starward.RPC.GameInstall.SophonPatchDeleteFileCollection
	9, // 7: Starward.RPC.GameInstall.SophonPatchDeleteFileCollection.delete_files:type_name -> Starward.RPC.GameInstall.SophonPatchDeleteFile
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_Sophon_proto_init() }
func file_Sophon_proto_init() {
	if File_Sophon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Sophon_proto_rawDesc), len(file_Sophon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Sophon_proto_goTypes,
		DependencyIndexes: file_Sophon_proto_depIdxs,
		MessageInfos:      file_Sophon_proto_msgTypes,
	}.Build()
	File_Sophon_proto = out.File
	file_Sophon_proto_goTypes = nil
	file_Sophon_proto_depIdxs = nil
}
